server:
  port: 8080
  error.include-message: always
springdoc:
  swagger-ui:
    path: /swagger-ui
spring:
  application.name: bird-service
  main.web-application-type: REACTIVE
  profiles.active: local
  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS: false
    deserialization.fail-on-unknown-properties: false
    default-property-inclusion: non_null
  data:
    mongodb:
      uri: mongodb+srv://dbtec:SvmFHPpCMF9dom9D@cluster0.1dwxw2n.mongodb.net/?retryWrites=true&w=majority
      database: ${spring.application.name}

client:
  4devs:
    url: https://www.4devs.com.br